# Default: build URI from host/username/password/auth-db
spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.username}:${mongodb.password}@${mongodb.host}/${mongodb.auth-db}
      database: ${mongodb.database}
---
# Dummy values when MongoDB is disabled (profile no-mongodb); Mongo auto-config is excluded so these are not used.
spring.config.activate.on-profile: no-mongodb
mongodb:
  uri: ""
  username: ""
  password: ""
  host: localhost
  database: default
  auth-db: admin

---
# Use full URI when set (e.g. Render + Atlas: set MONGODB_URI and MONGODB_DATABASE)
spring.config.activate.on-profile: mongodb-uri
spring:
  data:
    mongodb:
      uri: ${mongodb.uri}
      database: ${mongodb.database}
---
spring.config.activate.on-profile: local, local-perf
mongodb:
  host: localhost:27017
  username: root
  password: password123
  database: ice-cash-local
  auth-db: admin?ssl=false
---
spring.config.activate.on-profile: local-docker
mongodb:
  host: mongodb-primary:27017
  username: root
  password: password123
  database: ice-cash-local
  auth-db: admin?ssl=false
