spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/changelog/${liquibase.change-log-file}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icecash?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Africa/Harare
    username: root
    password: 123456
liquibase.change-log-file: liquibase-db-changelog-test.xml
---
spring.config.activate.on-profile: local-perf
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icecash_perf?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Africa/Harare
    username: root
    password: 123456
liquibase.change-log-file: liquibase-db-changelog.xml
---
spring.config.activate.on-profile: dev-k8s
spring:
  datasource:
    url: ${tidb.url}
    username: ${tidb.username}
    password: ${tidb.password}
---
spring.config.activate.on-profile: dev-mysql-k8s
spring:
  datasource:
    url: ${mariadb.url}
    username: ${mariadb.username}
    password: ${mariadb.password}
---
spring.config.activate.on-profile: dev-k8s-perf
spring:
  datasource:
    url: ${perf.tidb.url}
    username: ${tidb.username}
    password: ${tidb.password}
liquibase.change-log-file: liquibase-db-changelog.xml
---
spring.config.activate.on-profile: dev-mysql-k8s-perf
spring:
  datasource:
    url: ${perf.mariadb.url}
    username: ${mariadb.username}
    password: ${mariadb.password}
liquibase.change-log-file: liquibase-db-changelog.xml
---
spring.config.activate.on-profile: uat-k8s-perf
spring:
  datasource:
    url: ${perf.mariadb.url}
  liquibase:
    change-log: classpath:/db/changelog/${perf.liquibase.change-log-file}
